services:
  - type: web
    name: student-project-hub
    runtime: python
    buildCommand: python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
